parameters:
    erdnaxelaweb.static_fake_design.taxonomy_entry_definition:
        thematic_tag:
            models:
                - name: tag1
                  identifier: tag1
                - name: tag2
                  identifier: tag2
            fields:
                name:
                    required: true
                    type: string
                identifier:
                    required: true
                    type: string
                parent:
                    required: false
                    type: taxonomy_entry
                    options:
                        type: thematic_tag
                        max: 1
