parameters:
#    erdnaxelaweb.static_fake_design.generator.image.provider: ~
#    erdnaxelaweb.static_fake_design.generator.image.provider_parameters: {category: null, randomize: false, word: null, gray: true, format: 'png'}

    erdnaxelaweb.static_fake_design.enable_fake_generation: true

    erdnaxelaweb.static_fake_design.generator.image.provider: "\\Smknstd\\FakerPicsumImages\\FakerPicsumImagesProvider"
    erdnaxelaweb.static_fake_design.generator.image.provider_parameters: {randomize: false, gray: false}
    erdnaxelaweb.static_fake_design.generator.locale: "en_US"

services:
    ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator:
        factory: ['ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGeneratorFactory', 'createGenerator']
        arguments:
            $imageProviderClass: '%erdnaxelaweb.static_fake_design.generator.image.provider%'
            $imageProviderParameters: '%erdnaxelaweb.static_fake_design.generator.image.provider_parameters%'
            $locale: '%erdnaxelaweb.static_fake_design.generator.locale%'

    erdnaxelaweb.static_fake_design.generator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ChainGenerator'

    ErdnaxelaWeb\StaticFakeDesign\Fake\ChainGenerator:
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $fakeTypeMatcher: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakeTypeMatcher'
            $enableFakeGeneration: '%erdnaxelaweb.static_fake_design.enable_fake_generation%'

    ErdnaxelaWeb\StaticFakeDesign\Fake\FakeTypeMatcher:

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\AudioGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $imageGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\ImageGenerator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'audio'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\BlockGenerator:
        lazy: true
        arguments:
            $blockConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\BlockConfigurationManager'
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $fieldGeneratorRegistry: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ContentGenerator\ContentFieldGeneratorRegistry'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'block'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\BreadcrumbGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $linkGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\LinkGenerator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'breadcrumb'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\ContentGenerator:
        lazy: true
        arguments:
            $breadcrumbGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\BreadcrumbGenerator'
            $contentConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\ContentConfigurationManager'
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $fieldGeneratorRegistry: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ContentGenerator\ContentFieldGeneratorRegistry'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'content'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\CoordinatesGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'coordinates'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\FormGenerator:
        lazy: true
        arguments:
            $generators: !tagged_iterator { tag: 'erdnaxelaweb.static_fake_design.form.field.generator', index_by: 'type' }
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $formFactory: '@form.factory'
            $requestStack: '@request_stack'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'form'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\FormFieldGenerator:
        lazy: true
        arguments:
            $generators: !tagged_iterator { tag: 'erdnaxelaweb.static_fake_design.form.field.generator', index_by: 'type' }
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'form_field'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\SearchFormGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $formFactory: '@form.factory'
            $requestStack: '@request_stack'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'search_form'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\ImageGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $imageConfiguration: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\ImageConfiguration'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'image'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\LinkGenerator:
        lazy: true
        arguments:
            $factory: '@knp_menu.factory'
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $translator: '@translator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'link'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\PagerGenerator:
        lazy: true
        arguments:
            $contentGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\ContentGenerator'
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $linkGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\LinkGenerator'
            $pagerConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\PagerConfigurationManager'
            $searchFormGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\SearchFormGenerator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'pager'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\RichTextGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'richtext'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\TaxonomyEntryGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $fieldGeneratorRegistry: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ContentGenerator\ContentFieldGeneratorRegistry'
            $taxonomyEntryConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\TaxonomyEntryConfigurationManager'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'taxonomy_entry'}

    ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\VideoGenerator:
        lazy: true
        arguments:
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $imageGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\ImageGenerator'
            $richTextGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\RichTextGenerator'
        tags:
            - {name: 'erdnaxelaweb.static_fake_design.generator', type: 'video'}
