parameters:
    erdnaxelaweb.static_fake_design.image.breakpoints:
        -
            suffix: desktop
            media: '(min-width: 1024px)'
            previewSize: '100%'
        -
            suffix: tablet
            media: '(min-width: 754px)'
            previewSize: '1024px'
        -
            suffix: mobile
            media: '(min-width: 0)'
            previewSize: '754px'

    erdnaxelaweb.static_fake_design.image.variations: []
    erdnaxelaweb.static_fake_design.block_definition: []
    erdnaxelaweb.static_fake_design.block_layout_definition: []
    erdnaxelaweb.static_fake_design.content_definition: []
    erdnaxelaweb.static_fake_design.taxonomy_entry_definition: []
    erdnaxelaweb.static_fake_design.pager_definition: []
    erdnaxelaweb.static_fake_design.display_functions_render_template: '@@StaticFakeDesign/static/display_functions.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ErdnaxelaWeb\StaticFakeDesignBundle\Controller\StaticController:
        public: true

    ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Renderer:
        arguments:
            $renderTemplate: '%erdnaxelaweb.static_fake_design.display_functions_render_template%'
            $blockConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\BlockConfigurationManager'

    ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Extension:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $componentBuilder: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentBuilder'
            $generator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ChainGenerator'
            $renderer: '@ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Renderer'

    ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Loader:
        decorates: twig.loader
        arguments:
            $innerLoader: '@ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Loader.inner'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\ImageConfiguration:
        arguments:
            $configuration:
                breakpoints: '%erdnaxelaweb.static_fake_design.image.breakpoints%'
                variations: '%erdnaxelaweb.static_fake_design.image.variations%'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\ContentConfigurationManager:
        lazy: true
        arguments:
            $fieldGeneratorRegistry: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ContentGenerator\FieldGeneratorRegistry'
            $definitions: '%erdnaxelaweb.static_fake_design.content_definition%'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\TaxonomyEntryConfigurationManager:
        lazy: true
        arguments:
            $fieldGeneratorRegistry: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ContentGenerator\FieldGeneratorRegistry'
            $definitions: '%erdnaxelaweb.static_fake_design.taxonomy_entry_definition%'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\BlockConfigurationManager:
        lazy: true
        arguments:
            $attributeGeneratorRegistry: '@ErdnaxelaWeb\StaticFakeDesign\Fake\BlockGenerator\AttributeGeneratorRegistry'
            $definitions: '%erdnaxelaweb.static_fake_design.block_definition%'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\BlockLayoutConfigurationManager:
        lazy: true
        arguments:
            $definitions: '%erdnaxelaweb.static_fake_design.block_layout_definition%'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\PagerConfigurationManager:
        lazy: true
        arguments:
            $definitions: '%erdnaxelaweb.static_fake_design.pager_definition%'

    ErdnaxelaWeb\StaticFakeDesignBundle\Command\CreateComponentCommand:
        arguments:
            $filesystem: '@filesystem'
