parameters:
    erdnaxelaweb.static_fake_design.image.breakpoints:
        -
            suffix: desktop
            media: '(min-width: 1024px)'
            previewSize: '100%'
        -
            suffix: tablet
            media: '(min-width: 754px)'
            previewSize: '1024px'
        -
            suffix: mobile
            media: '(min-width: 0)'
            previewSize: '754px'

    erdnaxelaweb.static_fake_design.image.variations: []
    erdnaxelaweb.static_fake_design.block_definition: []
    erdnaxelaweb.static_fake_design.block_layout_definition: []
    erdnaxelaweb.static_fake_design.content_definition: []
    erdnaxelaweb.static_fake_design.taxonomy_entry_definition: []
    erdnaxelaweb.static_fake_design.pager_definition: []
    erdnaxelaweb.static_fake_design.document_definition: []
    erdnaxelaweb.static_fake_design.display_functions_render_template: '@@StaticFakeDesign/static/display_functions.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ErdnaxelaWeb\StaticFakeDesignBundle\Controller\StaticController:
        public: true

    ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Renderer:
        arguments:
            $renderTemplate: '%erdnaxelaweb.static_fake_design.display_functions_render_template%'
            $definitionManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\DefinitionManager'

    ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Extension:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'
            $fakerGenerator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\FakerGenerator'
            $componentBuilder: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentBuilder'
            $generator: '@ErdnaxelaWeb\StaticFakeDesign\Fake\ChainGenerator'
            $renderer: '@ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Renderer'

    ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\BlockExtension:
        arguments:
            $requestStack: '@request_stack'

    ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Loader:
        decorates: twig.loader
        arguments:
            $innerLoader: '@ErdnaxelaWeb\StaticFakeDesign\Templating\Twig\Loader.inner'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\ImageConfiguration:
        arguments:
            $configuration:
                breakpoints: '%erdnaxelaweb.static_fake_design.image.breakpoints%'
                variations: '%erdnaxelaweb.static_fake_design.image.variations%'

    ErdnaxelaWeb\StaticFakeDesign\Configuration\DefinitionManager:
        lazy: true
        calls:
            - [registerDefinitions, [!php/const ErdnaxelaWeb\StaticFakeDesign\Definition\ContentDefinition::DEFINITION_TYPE, '%erdnaxelaweb.static_fake_design.content_definition%']]
            - [registerDefinitions, [!php/const ErdnaxelaWeb\StaticFakeDesign\Definition\TaxonomyEntryDefinition::DEFINITION_TYPE, '%erdnaxelaweb.static_fake_design.taxonomy_entry_definition%']]
            - [registerDefinitions, [!php/const ErdnaxelaWeb\StaticFakeDesign\Definition\PagerDefinition::DEFINITION_TYPE, '%erdnaxelaweb.static_fake_design.pager_definition%']]
            - [registerDefinitions, [!php/const ErdnaxelaWeb\StaticFakeDesign\Definition\BlockDefinition::DEFINITION_TYPE, '%erdnaxelaweb.static_fake_design.block_definition%']]
            - [registerDefinitions, [!php/const ErdnaxelaWeb\StaticFakeDesign\Definition\BlockLayoutDefinition::DEFINITION_TYPE, '%erdnaxelaweb.static_fake_design.block_layout_definition%']]
            - [registerDefinitions, [!php/const ErdnaxelaWeb\StaticFakeDesign\Definition\DocumentDefinition::DEFINITION_TYPE, '%erdnaxelaweb.static_fake_design.document_definition%']]

    ErdnaxelaWeb\StaticFakeDesignBundle\Command\CreateComponentCommand:
        arguments:
            $filesystem: '@filesystem'

    ErdnaxelaWeb\StaticFakeDesignBundle\Command\DumpDefinitionCommand:
        arguments:
            $definitionManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\DefinitionManager'

    ErdnaxelaWeb\StaticFakeDesign\Expression\ExpressionResolver:

    ErdnaxelaWeb\StaticFakeDesign\Document\DocumentBuilder:
        arguments:
            $expressionResolver: '@ErdnaxelaWeb\StaticFakeDesign\Expression\ExpressionResolver'
            $eventDispatcher: '@event_dispatcher'
