parameters:
    erdnaxelaweb.static_fake_design.showroom.base_dir: '%kernel.project_dir%/templates'
    erdnaxelaweb.static_fake_design.showroom.preview_layout: '@@StaticFakeDesign/showroom/layout/preview.html.twig'

services:
    ErdnaxelaWeb\StaticFakeDesignBundle\Controller\Showroom\ComponentController:
        public: true
        arguments:
            $componentFinder: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentFinder'
            $showroomHelper: '@ErdnaxelaWeb\StaticFakeDesign\Showroom\ShowroomHelper'
            $componentContextResolverFactory: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentContextResolverFactory'
            $componentParametersFormFactory: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentParametersFormFactory'
            $twig: '@twig'
            $router: '@router.default'
        calls:
            - ['setContainer', ['@service_container']]

    ErdnaxelaWeb\StaticFakeDesignBundle\Controller\Showroom\SidebarController:
        public: true
        arguments:
            $sidebarMenuBuilder: '@ErdnaxelaWeb\StaticFakeDesign\Showroom\Menu\SidebarMenuBuilder'
        calls:
            - ['setContainer', ['@service_container']]

    ErdnaxelaWeb\StaticFakeDesign\Component\ComponentFinder:
        arguments:
            $twig: '@twig'
            $baseDir: '%erdnaxelaweb.static_fake_design.showroom.base_dir%'

    ErdnaxelaWeb\StaticFakeDesign\Showroom\Menu\SidebarMenuBuilder:
        arguments:
            $factory: '@knp_menu.factory'
            $eventDispatcher: '@event_dispatcher'

    ErdnaxelaWeb\StaticFakeDesign\Component\ComponentContextResolverFactory:
        arguments:
            $fakeGenerator: '@erdnaxelaweb.static_fake_design.generator'

    ErdnaxelaWeb\StaticFakeDesign\Component\ComponentParameterTypeParser:

    ErdnaxelaWeb\StaticFakeDesign\Component\ComponentBuilder:
        arguments:
            $componentParameterTypeParser: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentParameterTypeParser'

    ErdnaxelaWeb\StaticFakeDesign\Showroom\ShowroomHelper:
        arguments:
            $imageConfiguration: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\ImageConfiguration'
            $previewLayout: '%erdnaxelaweb.static_fake_design.showroom.preview_layout%'

    ErdnaxelaWeb\StaticFakeDesign\Event\Subscriber\DefinitionSidebarMenu:
        arguments:
            $blockConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\BlockConfigurationManager'
            $contentConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\ContentConfigurationManager'
            $pagerConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\PagerConfigurationManager'
            $taxonomyEntryConfigurationManager: '@ErdnaxelaWeb\StaticFakeDesign\Configuration\TaxonomyEntryConfigurationManager'
            $router: '@router.default'
        tags:
            - { name: kernel.event_subscriber }

    ErdnaxelaWeb\StaticFakeDesign\Event\Subscriber\ComponentSidebarMenu:
        arguments:
            $router: '@router.default'
            $storiesFinder: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentFinder'
        tags:
            - { name: kernel.event_subscriber }

    ErdnaxelaWeb\StaticFakeDesign\Component\ComponentParametersFormFactory:
        arguments:
            $componentContextResolverFactory: '@ErdnaxelaWeb\StaticFakeDesign\Component\ComponentContextResolverFactory'
            $formFactory: '@form.factory'
